//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Pharmacie_V3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionPharmacieEntities : DbContext
    {
        public GestionPharmacieEntities()
            : base("name=GestionPharmacieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoginApp> LoginApps { get; set; }
        public virtual DbSet<TableForme> TableFormes { get; set; }
        public virtual DbSet<TableCategorie> TableCategories { get; set; }
        public virtual DbSet<TableFarmTarif> TableFarmTarifs { get; set; }
        public virtual DbSet<TableGrossiste> TableGrossistes { get; set; }
        public virtual DbSet<TableLabo> TableLaboes { get; set; }
        public virtual DbSet<TableProduit> TableProduits { get; set; }
    }
}
