//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Pharmacie_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableCategorie
    {
        public int CategorieID { get; set; }
        public string Categorie { get; set; }
    }
}
