//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Pharmacie_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableProduit
    {
        public int ProduitID { get; set; }
        public string CodeBarre { get; set; }
        public string DesignationPro { get; set; }
        public Nullable<decimal> Prixdachat { get; set; }
        public Nullable<decimal> PrixVente { get; set; }
        public string FormProduit { get; set; }
        public string CategorieProduit { get; set; }
        public Nullable<double> FamTarif { get; set; }
        public Nullable<int> ProduitActif { get; set; }
        public Nullable<int> QteStock { get; set; }
        public string Laboratoire { get; set; }
        public string Grossiste { get; set; }
    }
}
